In [2]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_parquet('../data/raw/raw_prices.parquet')
df.tail()

Ticker,ADI,AMD,AVGO,CRUS,INTC,LSCC,MCHP,MPWR,MRVL,MU,NVDA,NXPI,ON,QCOM,QRVO,SLAB,SMTC,STM,SWKS,TXN
Date,,,,,,,,,,,,,,,,,,,,
2026-02-27,354.679443,200.210007,319.549988,141.119995,45.610001,95.620003,74.639999,1142.739990,81.690002,412.369995,177.190002,227.009995,66.480003,141.451813,82.900002,204.529999,90.220001,33.610001,59.580002,212.110001
2026-03-02,351.309998,198.619995,318.820007,143.029999,45.500000,100.720001,74.309998,1142.579956,80.860001,412.670013,182.479996,224.759995,66.480003,140.130295,81.919998,204.910004,96.300003,33.480000,58.930000,209.820007
2026-03-03,338.989990,190.949997,313.839996,138.380005,43.099998,93.480003,71.389999,1074.369995,77.510002,379.679993,180.050003,215.250000,63.419998,137.248810,81.269997,203.639999,90.169998,31.620001,58.150002,202.669998
2026-03-04,341.510010,202.070007,317.529999,137.809998,45.580002,91.629997,69.900002,1099.020020,78.089996,400.769989,183.039993,216.369995,62.529999,138.619995,79.459999,203.580002,89.750000,33.330002,56.279999,202.389999
2026-03-05,329.720001,199.449997,332.769989,134.279999,45.950001,91.110001,67.809998,1078.439941,75.680000,397.049988,183.339996,210.580002,60.849998,137.000000,79.410004,203.250000,87.080002,33.310001,56.480000,197.979996

In [12]:
df_log = np.log((df)/(df.shift(1)))
df_log.tail()

Ticker,ADI,AMD,AVGO,CRUS,INTC,LSCC,MCHP,MPWR,MRVL,MU,NVDA,NXPI,ON,QCOM,QRVO,SLAB,SMTC,STM,SWKS,TXN
Date,,,,,,,,,,,,,,,,,,,,
2026-02-27,0.004055,-0.017183,-0.006706,-0.027261,0.003294,-0.016903,-0.004412,-0.032196,0.029820,-0.007706,-0.042538,-0.022734,-0.024957,-0.022435,0.005322,-0.000929,-0.002988,-0.022651,-0.000503,-0.002449
2026-03-02,-0.009545,-0.007973,-0.002287,0.013444,-0.002415,0.051962,-0.004431,-0.000140,-0.010212,0.000727,0.029418,-0.009961,0.000000,-0.009386,-0.011892,0.001856,0.065217,-0.003875,-0.010970,-0.010855
2026-03-03,-0.035698,-0.039382,-0.015743,-0.033051,-0.054189,-0.074597,-0.040088,-0.061554,-0.042312,-0.083320,-0.013406,-0.043233,-0.047122,-0.020777,-0.007966,-0.006217,-0.065772,-0.057158,-0.013324,-0.034671
2026-03-04,0.007406,0.056603,0.011689,-0.004128,0.055946,-0.019989,-0.021092,0.022684,0.007455,0.054059,0.016470,0.005190,-0.014133,0.009941,-0.022523,-0.000295,-0.004669,0.052668,-0.032687,-0.001383
2026-03-05,-0.035133,-0.013051,0.046879,-0.025949,0.008085,-0.005691,-0.030356,-0.018903,-0.031348,-0.009325,0.001638,-0.027124,-0.027235,-0.011755,-0.000629,-0.001622,-0.030201,-0.000600,0.003547,-0.022031